// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD.entidades;

public partial class Persona
{
    public int Idpersonas { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Cedula { get; set; }

    public string Activo { get; set; }
    public object[] Idpersona { get; internal set; }
}