// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRUD.infraestructura;

public partial class alumnoContext : DbContext
{
    public alumnoContext(DbContextOptions<alumnoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Personas> Personas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Personas>(entity =>
        {
            entity.HasKey(e => e.Idpersonas).HasName("PRIMARY");

            entity.ToTable("personas");

            entity.Property(e => e.Idpersonas)
                .HasColumnType("int(11)")
                .HasColumnName("idpersonas");
            entity.Property(e => e.Activo)
                .HasMaxLength(45)
                .HasColumnName("activo");
            entity.Property(e => e.Apellidos)
                .HasMaxLength(100)
                .HasColumnName("apellidos");
            entity.Property(e => e.Cedula)
                .HasMaxLength(10)
                .HasColumnName("cedula");
            entity.Property(e => e.Nombres)
                .HasMaxLength(100)
                .HasColumnName("nombres");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}